name: lzprices
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: 6.2.1
  http: ^1.2.1
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  supabase_flutter: ^2.5.3
  collection: ^1.18.0
  shared_preferences: ^2.2.3
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  provider: ^6.1.2
  get_it: ^7.7.0
  cloud_firestore: ^6.1.2
  timezone: ^0.9.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.9


flutter:


  uses-material-design: true
